### ISSUE TITLE
Make package URLs match Hackage

### ISSUE THREAD

**Issue by arrowd** [input-output-hk/cardano-haskell-packages#102]
When pulling the `foo-1.2.3` package from Hackage the following URL should be used:

https://hackage.haskell.org/package/foo-1.2.3/foo-1.2.3.tar.gz

However, for CHaP this form doesn't work and istead the following should be used:

https://input-output-hk.github.io/cardano-haskell-packages/package/foo-1.2.3.tar.gz

Would it be possible to make CHaP URLs match Hackage ones? This would simplify things for downstream packagers.

**Comment by michaelpj** [comment]
Can you elaborate on your use case? It works fine for Cabal.

**Comment by arrowd** [comment]
Many downstream packagers (including FreeBSD) are prefetching all required sources before the build to allow caching and to be able to disable network access during build. I implemented all the necessary machinery for multi-repository Cabal projects, but it turned out that URL patterns are different. I just wanted to make it easy for me, if it is cheap to implement on your side.

**Comment by michaelpj** [comment]
The only robust way to do that is to get cabal to do it for you, I think. I don't think we want to promise that we will always match the layout of Hackage if that's not a requirement on Cabal package repositories.

**Comment by michaelpj** [comment]
@andreabedini

**Comment by arrowd** [comment]
Interestingly, Stackage URLs also do not have that extra `/foo-1.2.3/` part. I wonder if it is because both CHaP and Stackage do not support package revisions, only Hackage does. In this case, I think, nothing should be done on the CHaP side.

**Comment by andreabedini** [comment]
Interesting, thanks for bringing this up @arrowd. I originally based my code on what [`hackage-repo-tool`](https://github.com/haskell/hackage-security/tree/master/hackage-repo-tool) does and never really dug into the details once I saw the code working. Looking at the [code](https://github.com/haskell/cabal/blob/6cd29789ca866464dc3af89f62c98c41264ce3cd/cabal-install/src/Distribution/Client/FetchUtils.hs#L309-L326) It turns out both schemes are kind of correct: the long one is a legacy one, the short one is the new. I don't know if there's a fallback between the two.

```haskell
-- | Generate the URI of the tarball for a given package.
--
packageURI :: RemoteRepo -> PackageId -> URI
packageURI repo pkgid | isOldHackageURI (remoteRepoURI repo) =
  (remoteRepoURI repo) {
    uriPath = FilePath.Posix.joinPath
      [uriPath (remoteRepoURI repo)
      ,prettyShow (packageName    pkgid)
      ,prettyShow (packageVersion pkgid)
      ,prettyShow pkgid <.> "tar.gz"]
  }
packageURI repo pkgid =
  (remoteRepoURI repo) {
    uriPath = FilePath.Posix.joinPath
      [uriPath (remoteRepoURI repo)
      ,"package"
      ,prettyShow pkgid <.> "tar.gz"]
  }
```

**Comment by arrowd** [comment]
I wonder how revision URLs look like in the new scheme.

**Comment by andreabedini** [comment]
My understanding is that revisions are not fetched by url but are read off the index file (which contains all the cabal files of all the packages).

**Comment by arrowd** [comment]
Fetching by URL works for Hackage. I suppose the index file contains only the last revision?

**Comment by andreabedini** [comment]
I think I didn't explain myself well.

Hackage exposes a large api [hackage.haskell.org/api](https://hackage.haskell.org/api) but to build a project cabal only uses two bits:

1) the index file https://hackage.haskell.org/01-index.tar.gz
2) the package tarballs https://hackage.haskell.org/package/package-id.tar.gz (as above)

The index file is append-only and contains all the cabal files of all packages and their revisions (plus some other metadata like preferred versions and the hashes of the package tarballs).

The index file alone is enough for cabal to orchestrate a build, but it needs to download the package tarball to actually execute them. In particular cabal never downloads the revisions from the url since they are all already included in the index file (even older revisions).

**Comment by michaelpj** [comment]
I'm closing this with "working as reasonably intended".
